name: Run pre-commit and autofix

on:
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - uses: pre-commit/action@v3.0.1

      - uses: pre-commit-ci/lite-action@v1.1.0
        if: always()
