
name: Package release

on:
  release:
    types:
      - created


jobs:
  release-build:
    name: Release
    runs-on: ubuntu-latest
    env:
      RUNNER_OS: "windows"
      CI: "1"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Package wheel
        run: |
          pip install build twine
          python -m build . --wheel --sdist
      - name: upload dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
